name: Atualizar API Tesouro Direto

on:
  schedule:
    - cron: '30 11 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Executar Scraper
        run: node scraper.cjs

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
